<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="http://www.baeldung.com/springsoap/gen"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             targetNamespace="http://www.baeldung.com/springsoap/gen"
             name="CountriesService">

    <types>
        <xsd:schema targetNamespace="http://www.baeldung.com/springsoap/gen">
            <xsd:import namespace="http://www.baeldung.com/springsoap/gen" schemaLocation="countries.xsd"/>
        </xsd:schema>
    </types>

    <message name="GetCountryRequest">
        <part name="body" element="tns:getCountryRequest"/>
    </message>

    <message name="GetCountryResponse">
        <part name="body" element="tns:getCountryResponse"/>
    </message>

    <portType name="CountriesPortType">
        <operation name="getCountry">
            <input message="tns:GetCountryRequest"/>
            <output message="tns:GetCountryResponse"/>
        </operation>
    </portType>

    <binding name="CountriesBinding" type="tns:CountriesPortType">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" use="literal"/>
        <operation name="getCountry">
            <soap:operation soapAction="http://www.baeldung.com/springsoap/gen/getCountry"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>

    <service name="CountriesService">
        <documentation>Dummy SOAP service for consuming country information</documentation>
        <port name="CountriesPort" binding="tns:CountriesBinding">
            <soap:address location="http://localhost:8080/ws/countries"/>
        </port>
    </service>

</definitions>
