package com.example.petclinic.service

import com.example.soap.countries.CountriesService
import com.example.soap.countries.CountriesPortType
import com.example.soap.countries.GetCountryRequest
import com.example.soap.countries.GetAllCountriesRequest
import com.example.soap.countries.FilterCriteria
import com.example.soap.countries.Currency
import org.springframework.stereotype.Service

@Service
class RemoteCountryService {
    private val countryService: CountriesPortType by lazy {
        CountriesService().getCountriesPort()
    }

    fun send() {
        val req = GetCountryRequest()
        req.name = "Germany"
        countryService.getCountry(req)
    }

    fun sendGetAllCountries() {
        val getAllReq = GetAllCountriesRequest()
        getAllReq.isIncludeDetails = true

        // Build nested FilterCriteria with currency filter
        val filterCriteria = FilterCriteria()
        filterCriteria.region = "Europe"
        filterCriteria.minPopulation = 1000000L
        filterCriteria.maxPopulation = 100000000L

        // Create nested Currencies wrapper (this is an inner class generated by JAXB)
        val currenciesWrapper = FilterCriteria.Currencies()
        currenciesWrapper.currency.add(Currency.EUR)
        currenciesWrapper.currency.add(Currency.GBP)
        currenciesWrapper.currency.add(Currency.PLN)
        filterCriteria.currencies = currenciesWrapper

        getAllReq.filterCriteria = filterCriteria

        countryService.getAllCountries(getAllReq)
    }
}
